### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by aj-centexbel** [monkeylearn/monkeylearn-python#13]
It would be nice to have the possibility to define proxy settings. In corporate environment, the request is not possible easily.

**Comment by gonz** [comment]
Hey @aj-centexbel Currently you can't pass proxy settings when initializing the `MonkeyLearn` class  but since we're using [requests](http://docs.python-requests.org/en/master/) internally you can just set the appropriate [environment variables](http://docs.python-requests.org/en/master/user/advanced/#proxies).
